---
- name: reboot
  hosts: "{{ host_alias }}"
  become: yes
  become_user: root

  tasks:
    - name: Reboot
      reboot:
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
