---
- name: wait vm
  hosts: "{{ vm }}"
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: Wait 300 seconds, but only start checking after 30 seconds
      wait_for_connection:
        delay: 30
        timeout: 300
